ladybug-tools/honeybee-energy

.releaserc.json, .travis.yml, deploy.sh, honeybee_energy/idealair.py, honeybee_energy/load/infiltration.py, honeybee_energy/properties/aperture.py, honeybee_energy/properties/door.py, honeybee_energy/properties/face.py, honeybee_energy/properties/model.py, honeybee_energy/properties/room.py, honeybee_energy/properties/shade.py, honeybee_energy/simulation/__init__.py, honeybee_energy/simulation/control.py, honeybee_energy/simulation/daylightsaving.py, honeybee_energy/simulation/runperiod.py, honeybee_energy/simulation/shadowcalculation.py, honeybee_energy/simulation/sizing.py, honeybee_energy/simulationparameter.py, tests/idealair_test.py, tests/simulation_control_test.py, tests/simulation_runperiod_test.py, tests/simulation_shadowcalculation_test.py, tests/simulation_sizing_test.py, tests/simulationparameter_test.py
This commit adds all of the objects needed to describe basic parameters of the EnergyPlus simulation including:
* RunPeriod (including start day of week, holidays and daylight savings time)
* Timestep
* ShadowCalculation
* SimulationControl
* SizingParameter
@mostaphaRoudsari , all of the code here is ready for review but I still have to write tests for all of the objects (I will do this soon).
In addition to reviewing the code, I could use your thoughts on one structural decision that I know relates to how things will run on the cloud service.  Right now, the `SimulationParameter` schema (with all of the settings needed for the EnergyPlus simulation) is completely separate for the `Model` schema.  However, we know that at the end of the day, all of this info ends up in the same OSM and …
=> feat(simulation): Add objects for EnergyPlus simulation settings

honeybee_energy/_extend_honeybee.py, honeybee_energy/properties/model.py, honeybee_energy/schedule/day.py, honeybee_energy/simulation/output.py, honeybee_energy/simulation/sizing.py, honeybee_energy/simulationparameter.py, honeybee_energy/writer.py, tests/aperture_extend_test.py, tests/door_extend_test.py, tests/model_extend_test.py, tests/room_extend_test.py, tests/shade_extend_test.py, tests/simulation_output_test.py
Working with the new structure of honeybee-core writers. This commit officially brings everything together to make a simulate-able IDF!
=> feat(writer): Add writer objects to go to.idf

honeybee_energy/__init__.py, honeybee_energy/programtype.py, honeybee_energy/schedule/ruleset.py
There are also a few edits here to the standards gem methods to get them to work with the cleaned data in `honeybee_energy_standards`.  The next PR that I send here will remove these methods, though, and I will have them code-injected form `honeybee_energy_standards`.
=> refactor(init): Edit __init__.py to load honeybee_energy extensions

README.md, honeybee_energy/properties/face.py, honeybee_energy/properties/room.py, requirements.txt
The readme now includes all of the standard info about how to install and develop with the library. I also took the opportunity to fix a couple of typos in the module and add a minimum version number to the dependencies.
=> docs(readme): Update README to current standard

honeybee_energy/idealair.py, honeybee_energy/load/setpoint.py, honeybee_energy/load/ventilation.py, honeybee_energy/properties/room.py, honeybee_energy/writer.py, tests/idealair_test.py, tests/load_setpoint_test.py, tests/load_ventilation_test.py, tests/model_extend_test.py
Without including the room name, we ultimately end up with duplicate thermostats and ventilation objects in the IDF when we have more than one Room.
=> fix(to_idf): Include room name in the name of thermostat and ventilation

honeybee_energy/schedule/ruleset.py
When there are no design day schedules assigned, the ScheduleRuleset is supposed to default to the default_day_schedule. This commit fixes this issue.
=> fix(ruleset): Fix bug in translating ScheduleRuleset to_idf

honeybee_energy/schedule/rule.py, honeybee_energy/schedule/ruleset.py, honeybee_energy/writer.py, tests/idf/cross_referenced_schedule_day.idf, tests/schedule_ruleset_test.py, tests/simulationparameter_test.py
This fixes the bug found by @zha and reported in this issue: https://github.com/ladybug-tools/honeybee-energy/issues/56
Specifically, it addresses cases where the same ScheduleDay is referenced by multiple ScheduleWeeks in an IDF file.  This doesn't map as cleanly to the ScheduleRuleset schema or, rather, it creates cases where someone can edit the ScheduleDay of one ScheduleRule and this inadvertently edits the ScheduleDay of another ScheduleRule. I realize that this "inadvertent editing" situation happens in the IDF world and no one minds but we also know that the IDF world is mostly concerned with storing schedules for individual Models and really isn't meant to manage a library of schedules as honeybee is. This is apparent in the fact that IDF makes it difficult to view year schedules …
=> fix(ruleset): Bug fix to ScheduleRuleset.extract_all_from_idf_file

MANIFEST.in, honeybee_energy/config.json, honeybee_energy/config.py, honeybee_energy/lib/_loadconstructions.py, honeybee_energy/lib/_loadconstructionsets.py, honeybee_energy/lib/_loadprogramtypes.py, honeybee_energy/lib/_loadschedules.py, honeybee_energy/lib/_loadtypelimits.py, honeybee_energy/run.py, honeybee_energy/writer.py, setup.py, tests/config_test.py
The config file handles several commonly-accessed folders including the folders for openstudio/ energyplus installations, the user-defined library of templates (eg. constructions, schedules, etc.), the default simulation folder, and the location of the energy_model_measure.
=> feat(config): Add a config module to handle folder locations

honeybee_energy/config.py, honeybee_energy/run.py
I got the chance to borrow Rosi's Macbook for a few hours and it was enough for me to develop and test some functions that could run EnergyPlus successfully on Mac. This commit also includes a bug fix to the previous code that I had implemented to find the EnergyPlus/OpenStudio installation on Mac.
=> feat(run): Add methods to run EnergyPlus/OpenStudio on Unix

honeybee_energy/config.py, honeybee_energy/simulation/output.py
Thanks to something @mingbopeng pointed out, I realized that the code to find the latest versions of EnergyPlus and OpenStudio was not correct. This should fix it.
=> fix(config): Bug fix to the code that finds E+/OpenStudio versions

honeybee_energy/load/ventilation.py, honeybee_energy/schedule/fixedinterval.py, honeybee_energy/schedule/rule.py, honeybee_energy/simulation/parameter.py, honeybee_energy/simulation/shadowcalculation.py, honeybee_energy/simulation/sizing.py, tests/ddy/chicago.ddy, tests/ddy/chicago_monthly.ddy, tests/simulation_parameter_test.py, tests/simulation_sizing_test.py
Since these ultimately end up in the IDF and OSM, I think it makes sense to include them within the Python objects here rather than have users upload a .ddy file that might often have more design days than they actually need.
=> feat(sizing): Add design_days to the SizingParameter object

honeybee_energy/config.json, honeybee_energy/config.py, honeybee_energy/construction/dictutil.py, honeybee_energy/lib/_loadconstructions.py, honeybee_energy/lib/_loadconstructionsets.py, honeybee_energy/lib/_loadmaterials.py, honeybee_energy/lib/_loadprogramtypes.py, honeybee_energy/lib/_loadschedules.py, honeybee_energy/lib/constructions.py, honeybee_energy/lib/constructionsets.py, honeybee_energy/lib/materials.py, honeybee_energy/lib/programtypes.py, honeybee_energy/lib/schedules.py
This commit shifts the burden of loading data that extends the standards to honeybee_energy. This way, the only thing that standards extensions need to worry about is providing the data and not any of the code that does the extending.
This also makes it possible to put the honeybee_energy_standards data in a more central location (away from the Python packages) so that it can be used by other plugins.
=> feat(lib): Add methods to automatically load extensions

honeybee_energy/config.py, honeybee_energy/construction/air.py, honeybee_energy/construction/opaque.py, honeybee_energy/construction/window.py, honeybee_energy/constructionset.py, honeybee_energy/programtype.py, honeybee_energy/properties/aperture.py, honeybee_energy/properties/door.py, honeybee_energy/properties/face.py, honeybee_energy/properties/room.py, honeybee_energy/properties/shade.py, honeybee_energy/schedule/fixedinterval.py, honeybee_energy/schedule/ruleset.py
Hi @chriswmackey 
I hope I got these right, I did my best to figure out the keys and differences between from_dict and from_dict_abridged but I feel pretty good.
One minor comment I think the 'layers' key was missing from the WindowConstruction.from_dict() example. I added it, hope that's okay.
Please let me know if I got these right, Note also in same cases I specified 'str' in 'name' fields , you might have better options for some of these.
=> Add dictionary format examples in from_dict()  docstrigs

honeybee_energy/result/colorroom.py, honeybee_energy/run.py
I realized that the in.idf spit out by OpenStudio CLI contains a lot of extra stuff that interferes with honeybee and the pre-preprocess.idf is just the pure output from running the measures. So this changes the honeybee run commands to use the pre-preprocess.idf.
=> fix(run): Simulate pre-preprocess.idf output from OpenStudio CLI

honeybee_energy/config.py, honeybee_energy/run.py
This commit adds code that prioritizes the searching of data and engines within the ladybug_tools installation folder. The code to find installations of OpenStudio and EnergyPlus in their default locations still exists but this code is only executed if no OpenStudio installations were found in the ladybug_tools folder.
=> fix(config): Update config to use new ladybug_tools install folder

honeybee_energy/constructionset.py, honeybee_energy/lib/_loadconstructions.py, honeybee_energy/lib/_loadconstructionsets.py, honeybee_energy/lib/_loadprogramtypes.py, honeybee_energy/lib/_loadschedules.py
This commit makes the ConstructionSet schema more easily deconstructable/editable.
It also ensures that non-abridged objects can be added to the standards library without issues.
=> feat(constructionset): Refactor ConstructionSet schema

dev-requirements.txt, honeybee_energy/config.py
This error has come up twice now that I see people tend to create a lot of folders that start with openstudio. This commit allows honeybee to not crash when this happens or, if it does, it gives a much more useful error.
=> fix(config): Catch errors with auto-sorting of OpenStudio version

honeybee_energy/cli/translate.py, honeybee_energy/properties/model.py, honeybee_energy/simulation/parameter.py, honeybee_energy/writer.py, requirements.txt, tests/model_extend_test.py, tests/simulation_parameter_test.py
After some discussions with @mostaphaRoudsari , we have decided that the north should not be a property of the Model for the same reason why we don't have the location as a part of the model. The north direction is a property of the simulation assets like the skies used in Radiance or the simulation parameters used in our EnergyPlus.
=> fix(model): Remove north from Model properties

honeybee_energy/run.py
I realized that I need this method on the interface end whenever I run OpenStudio CLI to completion (not just measures).
=> fix(run): Make output_energyplus_files public

honeybee_energy/result/colorobj.py, requirements.txt
Thinking it over, I can't picture any case where someone wants to have their E+ results in kWh/mm2 or kBtu/in2.  So I'm editing the colorobj module to do the conversion in the event that the geometry is in mm or inches.
=> fix(colorobj): Handle cases of models in inches or mm

honeybee_energy/cli/simulate.py, honeybee_energy/cli/translate.py, honeybee_energy/simulation/parameter.py
This commit updates the "simulate" command so that design days don't have to be specified if there is a .ddy file next to the .epw.
cc: @MingboPeng
=> feat(cli): Automatically pull design days from .ddy if not specified

honeybee_energy/construction/_base.py, honeybee_energy/construction/air.py, honeybee_energy/construction/dictutil.py, honeybee_energy/construction/opaque.py, honeybee_energy/construction/window.py, honeybee_energy/construction/windowshade.py, honeybee_energy/constructionset.py, honeybee_energy/lib/_loadconstructions.py, honeybee_energy/lib/constructions.py, honeybee_energy/material/shade.py, honeybee_energy/properties/aperture.py, honeybee_energy/properties/door.py, honeybee_energy/properties/model.py, honeybee_energy/writer.py, tests/construction_test.py, tests/schedule_fixedinterval_test.py
This commit might be called a fix as much as it is a new feature. Long story short is that the way that blinds and shades were represented in the schema previously, they could never be simulated by EnergyPlus since E+ always needs a ShadingControl object in order to be able to simulate them.  So I added a new WindowConstructionShaded class to handle the creation of this ShadingControl object and allow users to change some of its properties.
I still have to add tests here and send parallel PRs to honeybee-schema and the honeybee-openstudio-gem but I have verified that it's working in the direct-to-idf case.
@mostaphaRoudsari , I mostly requested your review here to get your thoughts on the name of the new class: `WindowConstructionShaded`.  If my goal is to communicate that this is a …
=> feat(shades): Add support for Blinds and Shades a way that E+ supports

honeybee_energy/result/sql.py
The data collection classes have a flag on them to note that a range of criteria that are expected of timeseries data has been satisfied. I am setting this to true for all imported data to boost performance.
=> perf(sql): Ensure all imported data get validated analysis periods

.dockerignore, .releaserc.json, Dockerfile, deploy.sh
Note that the dockerfile hard codes the depdency versions (openstudio and honeybee-openstudio-gem). The image size for this implementation is roughly 550 MB.
#253
=> build(docker): set up docker container to run energy simulations using honeybee-energy

Dockerfile
This is technically CI but since we need a new docker image I'm pushing it as fix.
The issue was that pydantic and honeybee-schema were not installed successfully in Docker. There was also an error with Wheel not being installed.
The issue with Pydantic is most likely because we are currently install it for GitHub and not PyPI. For honeybee-schema we need to look into extras_require and if it can handle recursive dependencies. I'm not sure if honeybee-energy[cli] trigger honeybee-core[cli] successfully. If it was then we should have had honeybee-schema installed with no issues.
In any case, these changes will fix the issue for now so we can run honeybee-energy with no importing issues.
=> fix(docker): add missing modules to pip

honeybee_energy/cli/simulate.py
Openstudio and/or energyplus aren't too happy when provided with relative file paths for inputs so
this commit leverages click's path type to ensure certain input files exist and resolve the absolute
path to the file.
fix #272
=> fix(cli): simulate model command to resolve input abs path

honeybee_energy/cli/result.py, honeybee_energy/cli/settings.py, honeybee_energy/cli/simulate.py, honeybee_energy/cli/translate.py
This should mean that the use of relative paths are now supported throughout the CLI.
It also saved me several extra lines of code to have the file existence checks taken care of with the decorator.
Thanks for the original tip about this @AntoineDao .
=> fix(cli): Have honeybee-energy commands to use click.Path as the type

honeybee_energy/load/ventilation.py, honeybee_energy/material/glazing.py, honeybee_energy/material/opaque.py, honeybee_energy/material/shade.py, honeybee_energy/schedule/ruleset.py
I also implemented some changes such that the from_dict methods with materials don't mutate the dictionary that is input to them.
=> fix(from_idf): Improve from_idf methods with optional E+ fields

honeybee_energy/properties/aperture.py, honeybee_energy/properties/door.py, honeybee_energy/properties/model.py, honeybee_energy/properties/room.py, honeybee_energy/result/sql.py, honeybee_energy/ventcool/__init__.py, honeybee_energy/ventcool/control.py, honeybee_energy/ventcool/opening.py, honeybee_energy/writer.py, tests/result_test.py, tests/run_test.py, tests/ventcool_control_test.py, tests/ventcool_opening_test.py
This commit adds objects for simple window-based ventilative cooling. While this commit only includes enough objects to model windows with ZoneVentilation:WindandStackOpenArea objects, many of these objects should also be used in the future AFN.
@saeranv , Please feel free to review and post any questions that you have as comments. It may take me a day or two before I have enough tests in place to merge this in.  FYI, I am not expecting you to add any `to_idf` method as part of your work (you can see one of them in this PR). I only included this so that we have some way of exporting simple window-based ventilation objects in direct-to-idf workflows. I'm imagining that all of the AFN export happens through the honeybee_openstudio_gem.
=> feat(ventcool): Add objects for simple window-based ventilative cooling

honeybee_energy/config.py, honeybee_energy/properties/aperture.py, honeybee_energy/properties/door.py, honeybee_energy/properties/room.py, honeybee_energy/result/sql.py, honeybee_energy/simulation/output.py, honeybee_energy/ventcool/control.py, honeybee_energy/ventcool/opening.py, tests/ventcool_opening_test.py
This commit is primarily to fix an issue that I realized can arise from duplication of child objects (eg. HVAC systems or VentilationOpening objects) that have dependencies on parent honeybee-core objects (eg. Rooms, Apertures). The fix makes sure that the child objects get duplicated with the parent objects.
I also put in a few other small fixes:
* included the most recent openstudio version in the compatibility matrix of honeybee config.
* removed the JtoKWH converter in the diret-to-idf methods as I realized that this can never align with the OpenStudio workflows
* Added option to perform unit conversions from J to kWh upon import of summary report tables.
=> fix(properties): Ensure that child objects are duplicated with parents

honeybee_energy/hvac/__init__.py, honeybee_energy/hvac/_base.py, honeybee_energy/hvac/_template.py, honeybee_energy/hvac/allair/__init__.py, honeybee_energy/hvac/allair/_base.py, honeybee_energy/hvac/allair/furnace.py, honeybee_energy/hvac/allair/psz.py, honeybee_energy/hvac/allair/ptac.py, honeybee_energy/hvac/allair/pvav.py, honeybee_energy/hvac/allair/vav.py, honeybee_energy/hvac/doas/__init__.py, honeybee_energy/hvac/doas/_base.py, honeybee_energy/hvac/doas/fcu.py, honeybee_energy/hvac/doas/vrf.py, honeybee_energy/hvac/doas/wshp.py, honeybee_energy/hvac/heatcool/__init__.py, honeybee_energy/hvac/heatcool/_base.py, honeybee_energy/hvac/heatcool/baseboard.py, honeybee_energy/hvac/heatcool/evapcool.py, honeybee_energy/hvac/heatcool/fcu.py, honeybee_energy/hvac/heatcool/gasunit.py, honeybee_energy/hvac/heatcool/residential.py, honeybee_energy/hvac/heatcool/vrf.py, honeybee_energy/hvac/heatcool/windowac.py, honeybee_energy/hvac/heatcool/wshp.py, honeybee_energy/hvac/idealair.py, tests/hvac_allair_test.py, tests/hvac_doas_test.py, tests/hvac_heatcool_test.py, tests/hvac_idealair_test.py
This commit adds modules and classes for the ~120 HVAC templates that are available in the OpenStudio standards gem.
The classes don't do much computation but they serve the following purposes:
* Organizing/ classifying the 120 templates (grouping them into 16 classes)
* Providing documentation in the form of docstrings
* Handling serialization to dict
* Storing a few optional ECMs like heat recovery and economizers.
They way they are implemented it a bit like the Radiance modifiers in that most of the current functionality is handled by base classes from which everything inherits. But breaking down everything into 16 classes is useful as it means that we can extend the properties of ECMs that are available in the future.
=> feat(hvac): Add classes for detailed HVAC templates

honeybee_energy/properties/room.py, honeybee_energy/ventcool/control.py
This will help with applying window ventilation to dragonfly objects if no schedule is specified.
=> perf(ventcool): Only write schedule when it's not default

honeybee_energy/simulation/output.py
This commit ensures that simulations that request energy use results get the energy usage of ALL pieces of equipment contained within the various HVAC templates.
=> fix(output): Add energy use outputs for all the HVAC equipment

Dockerfile, honeybee_energy/simulation/output.py, honeybee_energy/ventcool/opening.py, tests/ventcool_opening_test.py
If we want to use the discharge coefficient in both simple ventilation and the AFN, it seems we should follow the E+ guide and use a coefficient that corresponds to the height from midpoint of lower opening to the neutral pressure level (deltaHnpl) instead of using the full height of the window.
=> fix(ventcool): Set default discharge coefficient to 0.45 for deltaHnpl

honeybee_energy/properties/model.py, honeybee_energy/ventcool/control.py
This commit fixes a bug where the Model's VentilationSimulationControl was not being preserved.
=> fix(ventcool): Preserve VentilationSimulationControl in serialization

honeybee_energy/properties/face.py, honeybee_energy/properties/model.py, honeybee_energy/properties/room.py, honeybee_energy/ventcool/afn.py, honeybee_energy/ventcool/crack.py, honeybee_energy/ventcool/opening.py, honeybee_energy/ventcool/simulation.py, tests/ventcool_afn_test.py
Now that the bounding box methods have been moved to ladybug_geometry, this commit refactors these functions out of honeybee_energy.  It also moves all of the aspect ratio methods not in ladybug_geometry onto the VentilationSimulationControl class instead of having everything as hidden methods within the afn module.
Lastly, a method was added to the ModelEnergyProperties to automatically compute building_type, long_axis_angle, and aspect_ratio from the Model's room geometry.
And I updated some of the docstrings to make it clear which properties have a bearing on the simulation in different situations.
=> fix(afn): Refactor methods for VentilationSimulationControl geometry

honeybee_energy/hvac/allair/vav.py, honeybee_energy/properties/room.py, honeybee_energy/ventcool/afn.py, honeybee_energy/ventcool/crack.py, honeybee_energy/ventcool/opening.py, tests/ventcool_afn_test.py
This commit ensures that the afn.genrate method recognizes Faces with an AirBoundary type and assigns them a Crack object with a very large flow coefficient.  This flow coefficient is derived from the Orifice Equation, using a discharge coefficient of 0.65 for an unobstructed opening.
=> fix(afn): Ensure AirBoundary Faces are properly represented in AFN

honeybee_energy/cli/__init__.py, honeybee_energy/cli/baseline.py, honeybee_energy/cli/translate.py, honeybee_energy/load/lighting.py, tests/cli_baseline_test.py, tests/load_lighting_test.py
This new property will provide a user interface for setting the lighting power density in the baseline model creation workflows.  This property is really only relevant when users are creating their own ProgramTypes from scratch (as opposed to using the ProgramTypes that come with the honeybee-energy-standards package).
The plan is that the baseline model creation workflows will first look for an equivalent ProgramType in the ASHRAE-2004 standard and use the LPD there.  If an equivalent ProgramType in 2004 is not found, this baseline_watts_per_area property will be used instead.  The default value for this property is the ASHRAE 2004 baseline for an office, which is the recommended approach when a given program cannot be classified into any of the categories of the ASHRAE standard.
=> fix(lighting): Add baseline_watts_per_area to Lighting class

Dockerfile, honeybee_energy/cli/baseline.py, setup.py
This commit adds the honeybee-energy-standards package into the docker file as it is required in order to run all of the new baseline model creation commands.
@mostaphaRoudsari  and @AntoineDao , please let me know if I am doing this correctly.  Also, adding in this package will likely increase the size of the docker image by 10 MBs so I am not totally sure this is worth it given that not all recipes will be using the honeybee-energy-standards package.  Let me know if you think we need to set up separate docker images depending on whether the standards package is needed.
=> fix(dockerfile): Add honeybee-energy-standards into Dockerfile

honeybee_energy/cli/__init__.py, honeybee_energy/config.py, tests/cli_main_test.py
This commit changes the check for EnergyPlus and OpenStudio version to parse the output of the --version command from the respective CLIs.  This will be much more reliable into the future as it does not rely on any version numbers being in the installation path.
I also added a `honeybee-energy config` command that returns a full JSON of configuration variables, including the version.
=> feat(config): Improve E+ and OS version check and add config command

honeybee_energy/load/people.py
OpenStudio doesn't translate the activity level schedule unless the unit type is "Activity Level". So this check will make sure everything happens as the schedule is assigned.
=> style(people): Improve activity level type check

honeybee_energy/properties/room.py, tests/room_extend_test.py
This includes the duplication of the room's current load object and all of the geometry math to convert the absolute load value to one that is normalized by area.
=> feat(room): Add methods to set absolute room loads

honeybee_energy/result/sql.py
It seems we were failing to catch the case of dimensionless units because EnergyPlus simple writes no units into the results for this case.  Such dimensionless data will now get the 'fraction' unit.
=> fix(sql): Catch the case of dimensionless/fractional units

honeybee_energy/config.py
Now that the from_honeybee folder has been removed, I am removing the check for it.
=> fix(config): Remove check for non-existent folder

Dockerfile, README.md
This PR should not be merged until we put the dockerhub credentials into Github so that the CI workflow runs successfully.
CC: @mostaphaRoudsari FYI
=> fix(docker): Update docker image to OpenStudio 3.1

Dockerfile, honeybee_energy/load/_base.py, honeybee_energy/load/equipment.py, honeybee_energy/load/hotwater.py, honeybee_energy/load/infiltration.py, honeybee_energy/load/lighting.py, honeybee_energy/load/people.py, honeybee_energy/load/setpoint.py, honeybee_energy/programtype.py, tests/programtype_test.py
I realized that we should shift the setpoint if all of the other schedules are being shifted.
I have also added a check that allows the user to not shift the schedules at all if they don't want to as part of the diversification process.
=> fix(load): Ensure Setpoint schedules are shifted

honeybee_energy/run.py
This will make it possible for us to return this clean model JSON from Pollination recipes so that it can be easily used for things like result-matching.
=> fix(cli): Standardize the name of clean model JSON sent to OpenStudio

honeybee_energy/measure.py
We should catch the case that there's no default for a choice argument.
=> style(measure): Small tweak to measure

honeybee_energy/cli/__init__.py, honeybee_energy/cli/edit.py, honeybee_energy/construction/air.py, honeybee_energy/construction/shade.py, honeybee_energy/construction/window.py, honeybee_energy/construction/windowshade.py, honeybee_energy/constructionset.py, honeybee_energy/material/_base.py, honeybee_energy/material/glazing.py, honeybee_energy/properties/model.py
This commit adds a command to assign all radiance modifiers based on energy properties.  This will be particularly useful in comfort mapping workflows.
=> feat(radiance): Add methods to assign modifiers based on constructions

honeybee_energy/cli/_helper.py, honeybee_energy/cli/lib.py, honeybee_energy/cli/settings.py, tests/cli_settings_test.py
I realized how annoying it is for people to be unable to change the north angle of their recipes.
I am also adding in some workarounds to that I can expose the run period for comfort maps, which I think will get used a lot.
=> fix(cli): Expose north angle on all simulation setting commands

honeybee_energy/cli/edit.py
The previous name was too vague and difficult to understand.
=> fix(cli): Rename command to modifiers-from-constructions

honeybee_energy/schedule/ruleset.py, tests/idf/OfficeOccupancySchedule_Compact.idf, tests/schedule_ruleset_test.py
Addresses issue #290
I gave it a try to implement a logic to parse Schedule:Compact components. I tried to follow the honeybee-energy API as much as possible.
=> Import Schedule:Compact as ScheduleRuleset

Dockerfile, build_image.sh, deploy.sh
- Reduce image size
- Refactor build into its own script for easier local testing
- To enable faster pulls
- Move blob getting to `build_image.sh`
- Refactor `deploy.sh`
- Base on `python:3.7-slim`
Reduces image size `1.42GB` -> `1.06GB`. Not amazing, but slightly better.
I tested this with:
1. `./build_image.sh hbe latest true`
2. `docker run -v $(realpath .)/tests:/home/ladybugbot/run/tests -it -v $(realpath .)/dev-requirements.txt:/home/ladybugbot/run/dev-requirements.txt hbe:latest bash`
3. (inside container now) `pip install -r dev-requirement.txt`
4. `python -m pytest tests/`
All tests should be passing.
=> feat(docker): improve image build

honeybee_energy/properties/room.py, honeybee_energy/ventcool/afn.py, tests/room_extend_test.py, tests/ventcool_afn_test.py
@chriswmackey 
This PR includes changes to the AFN infiltration calculation, and updated tests to better match infiltration flow through exterior area, including:
1. Incorporate the door and aperture infiltration (from edge cracks) with the area crack flow in their parent face. This is done by adding door and aperture area with parent area when scaling the normalized flow coefficient. 
2. Exposing the delta_pressure parameter for flow coefficient calculations, and modifying docstring to indicate how it should match simulated negative building pressure (relative to EP air node 1 to 2 custom result) to match constant interior flow rate per exterior area.
Note that, removing the edge crack flow (like we discussed in the forums) didn't make a huge difference, but I'm including it here since …
=> feat(afn.py): Modify crack logic to match constant infiltration flow.

honeybee_energy/construction/air.py, honeybee_energy/load/people.py
This will make it easier for people to build these objects when they are ok with accepting a standard "always on" type of default.
=> fix(scheudle): Ensure that activity and mixing schedules can be None

honeybee_energy/result/loadbalance.py, honeybee_energy/result/match.py
It seems that I misunderstood how the match.py module worked when I fist put together the load balance module. Now, I have tested it with multipliers and I'm pretty sure it works correctly.
=> fix(loadbalance): Ensure that load balance accounts for multipliers

honeybee_energy/construction/dynamic.py, honeybee_energy/construction/window.py, honeybee_energy/construction/windowshade.py, honeybee_energy/material/glazing.py, tests/construction_test.py, tests/material_glazing_test.py
I am following the simple methods used in the EnergyPlus Reference as noted in this discussion:
https://discourse.ladybug.tools/t/how-to-define-glassmat-layers-to-target-specific-shgc-and-u-value/15400/10
=> fix(construction): Add SHGC property to WindowConstruction

honeybee_energy/construction/dynamic.py, honeybee_energy/construction/window.py, honeybee_energy/construction/windowshade.py, honeybee_energy/material/glazing.py, tests/construction_test.py, tests/material_glazing_test.py
It seems that I was forgetting to account for back reflected solar in the calculation of solar transmittance. This commit fixes this issue and will make the SHGC ore accurate.
=> fix(window): Account for inter-reflection in transmittance calculations

honeybee_energy/cli/translate.py, honeybee_energy/construction/window.py, honeybee_energy/properties/model.py, honeybee_energy/run.py, honeybee_energy/writer.py
This ensures that window constructions get represented in gbXML with all of their properties. It also ensures that we pass volume, and ceiling height to the IDF to ensure EnergyPlus does not fail.
=> fix(model): Pass autocalculated parameters to OSM, IDF, gbXML

honeybee_energy/properties/model.py
We will just pass the single list of vertices as a property to the honeybee-openstudio-gem.
=> fix(model): Add property to pass holes to OSM/IDF

honeybee_energy/result/err.py
We are already doing a check for this before we export the model and so this warning from EnergyPlus is meaningless. We should remove it so that people don't get confused.
=> fix(err): Ignore degenerate surfaces warning

honeybee_energy/cli/simulate.py, honeybee_energy/run.py, tests/cli_simulate_test.py
The implementation is pretty hacky but this is just what we have to do if we don't want a separate recipe for each file type.
=> fix(simulate): Add support of OSM and IDF in "simulate model" command

honeybee_energy/properties/model.py
After this is merged, we can get rid of the use of OpenStudio's reorderULC. This will make things consistent between the export of IDFs through OpenStudio and those done with the direct-to-idf methods.
=> fix(model): Ensure use of upper-left vertices for shapes with holes

honeybee_energy/constructionset.py, honeybee_energy/properties/face.py, honeybee_energy/properties/model.py
I am also loosening the restriction on requiring AirBoundary Faces to use Construction:AirBoundary. It seems that Construction:AirBoundary can be fragile in some cases and it's just preferable to use an opaque construction.
=> fix(model): Use correct property to add vertices for faces with holes

honeybee_energy/cli/translate.py, honeybee_energy/hvac/allair/_base.py, honeybee_energy/hvac/doas/_base.py, honeybee_energy/hvac/heatcool/_base.py, honeybee_energy/hvac/idealair.py, honeybee_energy/measure.py, honeybee_energy/properties/room.py, honeybee_energy/writer.py, tests/model_extend_test.py
This means that virtually all Honeybee models can now be translated through the direct-to-idf pathway.
I'm also taking the opportunity to improve some of the error messages and improve the model-to-osm command.
=> feat(hvac): Add methods to convert detailed HVAC to Ideal Air equivalent

honeybee_energy/hvac/_base.py, honeybee_energy/hvac/idealair.py, honeybee_energy/properties/extension.py
Following the same pattern from #823 ,  adding a new **.properties** to HB-E [hvac.IdealAirSystem](https://github.com/ladybug-tools/honeybee-energy/blob/4cfb86c040a4587d8bb48715db37749040e82d4c/honeybee_energy/hvac/idealair.py#L15) class in order to allow for extension by plugins.
All hvac tests pass
Note: for consistency, I can add .properties to the rest of the hvac classes if you would like? (allair, doas, heatcool)
=> feat(properties) add properties that can be extended

honeybee_energy/material/opaque.py, tests/material_opaque_test.py
Added greenroof material:
All tests pass except:
```def test_greenroof_init_from_idf():```
```
def parse_idf_string(idf_string, expected_type=None):
"""Parse an EnergyPlus string of a single object into a list of values.
Args:
idf_string: An IDF string for a single EnergyPlus object.
expected_type: Text representing the expected start of the IDF object.
(ie. WindowMaterial:Glazing). If None, no type check will be performed.
Returns:
ep_fields -- A list of strings with each item in the list as a separate field.
Note that this list does NOT include the string for the start of the IDF
object. (ie. WindowMaterial:Glazing)
"""
idf_string = idf_string.strip()
if expected_type is not None:
>           assert idf_string.startswith(expected_type), 'Expected EnergyPlus {} ' \
'but received a …
```
=> Added greenroof material

honeybee_energy/run.py
It seems the OpenStudio CLI still can't parse paths with non-ascii characters in them but at least we are not the blocker now.
=> style(run): Enable files with non-ascii characters to be written

honeybee_energy/properties/room.py, honeybee_energy/writer.py
More often than not, this is what people expect so I'm just going to treat rooms without setpoints as unconditioned.
=> fix(writer): Treat no setpoint the same as unconditioned

honeybee_energy/config.py
It seems that the Pollination installer is going to intentionally delete folders that we are meant to fall back on. So I'm adding a check that will just defer everything to the final fallback folder in the Python installation if the folders have been deleted.
=> fix(config): Add check to be sure user standards are set up correctly

honeybee_energy/hvac/heatcool/_base.py
This needs to be passed, even when it is unused.
=> fix(heatcool): Ensure that schedule_dict can still be passed

honeybee_energy/cli/settings.py
This seems desirable now that the simulate command can handle the lack of a DDY file.
=> fix(settings): Enable DDY file to be optional

honeybee_energy/cli/simulate.py
This will keep the SQLite file size small when people don't connect any simulation parameters on Pollination.
=> fix(simulate): Change default SimPar to have monthly frequency

honeybee_energy/cli/simulate.py, honeybee_energy/properties/model.py
More info is here:
https://discourse.ladybug.tools/t/energyplus-vertex-size-mismatch-with-lbt-1-5/19154/9?u=chris
=> fix(model): Address the case when holes are closest to upper-left vertex

honeybee_energy/material/_base.py, honeybee_energy/material/opaque.py, honeybee_energy/properties/extension.py
Adding a .properties (to allow for extension) to all EnergyMaterial objects, as per Issue #903 
- Added _properties slot to _EnergyMaterialBase and all EnergyMaterial subclasses
- Added new EnergyMaterial properties objects in extension.py
- Modified `__copy__`, `to_dict`, `from_dict` for all EnergyMaterials to ensure properties carry through
- All Material and Construction tests pass
=> Add properties to EnergyMaterial objects (as per Issue #903)

build_image.sh
It seems that there's a bug that makes OpenStudio 3.5 not installable in any place other than the default location. So we will have to revert just the docker image building for now.
=> fix(docker): Switch back Docker image to use OpenStudio 3.4

.github/workflows/ci.yaml, .gitignore, honeybee_energy/cli/translate.py, honeybee_energy/run.py
This will allow gbXML files to export that are meant to be cleaned up in some other software.
=> fix(translate): Add an option to triangulate non-planar quads

honeybee_energy/cli/translate.py
This will be useful in certain workflows where people request a sizing run to happen as part of the translation and no design days are provided in the simulation parameters.
=> fix(translate): Add an option for EPW file in model-to-osm command

honeybee_energy/ventcool/opening.py
Fix #959 by ensuring ensure opening's angle is smaller than 360 degree
=> Fix(ventcool) #959: Avoid angle greater than 360 degree

honeybee_energy/construction/air.py, honeybee_energy/result/loadbalance.py, honeybee_energy/writer.py, tests/model_extend_test.py
It seems that we have not been accounting for the shortwave solar reflected back out of the windows and this was causing some imbalances for buildings with very high solar loads.
The service hot water load also was not being interpreted correctly when room multipliers are used.
Lastly, I did some experiments with the air mixing across air boundaries and made some improvements that make these mixing objects more read-able in the IDF. It turns out that the actual issue with these mixing objects was that the simulation timestep was too low to model air mixing correctly. So the original code was actually fine. But I am going to leave the cleaner IDF implementation as is for now.
=> fix(loadbalance): Tweak a few of the load balance terms

honeybee_energy/material/frame.py, honeybee_energy/material/gas.py, honeybee_energy/material/glazing.py, honeybee_energy/material/shade.py, honeybee_energy/properties/extension.py
As discussed in [Issue #1038](https://github.com/ladybug-tools/honeybee-energy/issues/1038), this PR updates some Honeybee-Energy materials with a `.properties` to allow for extension. The affected classes have had their `to_dict`, `from_dict`, and `__copy__` methods modified as well to support these properties extensions, following the pattern from [PR#861](https://github.com/ladybug-tools/honeybee-energy/pull/861)
Honeybee-Energy Materials updated include:
- [EnergyWindowMaterialGlazing](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/glazing.py#L34)
- [EnergyWindowMaterialSimpleGlazSys](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/glazing.py# …
=> Add new Material Properties for Extension

honeybee_energy/material/_base.py, honeybee_energy/material/glazing.py, honeybee_energy/material/opaque.py, tests/material_opaque_test.py
It seems that this limitation was removed in EnergyPlus 9.5 with this PR:
https://github.com/NREL/EnergyPlus/pull/7847
=> fix(material): Remove the check for low thermal resistance

honeybee_energy/properties/model.py, honeybee_energy/properties/room.py, honeybee_energy/result/match.py
This includes removing the error about air boundaries, which no longer triggers a failure and adding a new check to be sure that the model is not too high above the ground level.
=> fix(docs): Update validation errors for the most recent E+
