- tests/face_extend_test.py
Face creation is updated to comply with the latest version of honeybee-core
> test(face_extend): fix failing test

- setup.py
> fix(pip): set include_package_data to True

- honeybee_energy/construction.py
- honeybee_energy/lib/_loadschedules.py
- honeybee_energy/lib/_loadtypelimits.py
- honeybee_energy/lib/idf/schedules/default.idf
- honeybee_energy/lib/schedules.py
- honeybee_energy/lib/scheduletypelimits.py
- honeybee_energy/load/__init__.py
- honeybee_energy/load/_base.py
- honeybee_energy/load/equipment.py
- honeybee_energy/load/lighting.py
- honeybee_energy/load/people.py
- honeybee_energy/programtype.py
- honeybee_energy/properties/shade.py
- honeybee_energy/schedule/fixedinterval.py
- honeybee_energy/schedule/ruleset.py
- tests/load_equipment_test.py
- tests/load_lighting_test.py
- tests/load_people_test.py
- tests/schedule_day_test.py
This PR also contains a number of other tweaks and cleanups made along the way including:
* ensuring that the code of the ScheduleFixedInterval obeys the max character limit
* fixing some bugs in the setup of the schedule lib
* fixing a bug in the locking of constructions/schedules assigned to Shades
@mostaphaRoudsari ,
If you are able to review this relatively quickly (before the end of today), we can hopefully merge it in soon and this will make my PRs overall a bit more bite-size.  Otherwise, I may add the rest of the load objects (infiltration, ventilation and ProgramType) to this PR tomorrow.
> feat(load): Add objects to specify people, lighting and equipment

- .travis.yml
- tests/schedule_fixedinterval_test.py
I am just adding a few tests that I use to generate the samples for energy-model-schema validation.
> feat(schedule): Add more tests for ScheduleFixedInterval

- honeybee_energy/simulation/output.py
- honeybee_energy/simulationparameter.py
- tests/model_extend_test.py
- tests/simulation_output_test.py
- tests/simulationparameter_test.py
This commit adds a module to facilitate the requesting of outputs from the simulation.
I still have to add a few more tests but the code is all ready for review, @mostaphaRoudsari .
> feat(output): Add module to handle simulation outputs

- honeybee_energy/construction/_base.py
- honeybee_energy/construction/opaque.py
- honeybee_energy/construction/window.py
- honeybee_energy/writer.py
- tests/construction_test.py
This will be particularly helpful for checking that interior constructions are valid.
I am also moving a couple of properties from the opaque class to the _base class in order to make all of the methods on the _base class valid.
> feat(construction): Add is_symmetric property to Construction

- honeybee_energy/properties/model.py
I realized that the process of loading all the materials, constructions, schedules, etc. from a dictionary should be separate from the method that applies all of these objects to the Rooms, Faces, etc. of the Model.  This will help save a lot of code duplication in Dragonfly.
> feat(model): Separate out method that loads objects from dict

- honeybee_energy/properties/model.py
Having things separated will hopefully this (originally large) method easier to understand and maintain.
> refactor(model): Break down to_dict into 3 smaller methods

- honeybee_energy/construction/shade.py
- honeybee_energy/material/glazing.py
- honeybee_energy/material/opaque.py
- honeybee_energy/material/shade.py
- tests/material_shade_test.py
... I also changed the default conductivity of the shade material to be more like a material people would use on the indoors (cotton)
> docs(material): Correcting wrong docstrings

- honeybee_energy/material/gas.py
- honeybee_energy/material/shade.py
- honeybee_energy/schedule/fixedinterval.py
- honeybee_energy/simulation/daylightsaving.py
- honeybee_energy/simulation/runperiod.py
- tests/material_shade_test.py
- tests/schedule_fixedinterval_test.py
This commit is coordinated with this change to the honeybee-schema:
https://github.com/ladybug-tools-in2/honeybee-schema/pull/11
> feat(schema): Replace use of Date in schema with arrays of two integers

- honeybee_energy/properties/room.py
- tests/room_extend_test.py
And I added a test to catch it in the future.
> fix(room): Fix typo in previous commit

- honeybee_energy/config.py
- honeybee_energy/run.py
This commit brings the repo up-to-date with the recent [name changes in the energy_model_measure](https://github.com/ladybug-tools-in2/energy-model-measure/pull/48)
> feat(run): Update to refelct name change in energy_model_measure

- tests/construction_test.py
- tests/idealair_test.py
- tests/model_extend_test.py
- tests/schedule_fixedinterval_test.py
- tests/schedule_ruleset_test.py
- tests/schedule_typelimit_test.py
- tests/simulation_parameter_test.py
This code now lives in the honeybee-schema repo.
> docs(tests): Remove sample file generation

- honeybee_energy/config.py
- honeybee_energy/material/gas.py
- honeybee_energy/properties/model.py
- honeybee_energy/properties/shade.py
- honeybee_energy/writer.py
This commit brings the library in line with [this PR on honeybee-core](https://github.com/ladybug-tools/honeybee-core/pull/52).
> feat(door): Allow Shades to be assigned to Doors

- .gitignore
- README.md
- dev-requirements.txt
- docs/cli.rst
- docs/conf.py
- docs/index.rst
- honeybee_energy/__main__.py
- honeybee_energy/cli/__init__.py
- honeybee_energy/cli/simulate.py
- honeybee_energy/cli/translate.py
- honeybee_energy/config.py
- honeybee_energy/constructionset.py
- honeybee_energy/properties/aperture.py
- honeybee_energy/properties/door.py
- honeybee_energy/properties/face.py
- honeybee_energy/properties/shade.py
- honeybee_energy/run.py
- setup.py
- tests/aperture_extend_test.py
- tests/door_extend_test.py
- tests/face_extend_test.py
This commit adds a CLI to honeybee-energy to help with the process of translating Honeybee JSONs to OpenStudio Models and running honeybee JSONs through EnergyPlus.
I should add some more tests but I may just merge it in and add them later so that @mingbopeng has this to test his code.
> feat(cli): Add CLI to automate OpenStudio translation and simulation

- honeybee_energy/_extend_honeybee.py
- honeybee_energy/altnumber.py
- honeybee_energy/hvac/idealair.py
- honeybee_energy/lib/library/programtypes/default.json
- honeybee_energy/lib/programtypes.py
- honeybee_energy/load/people.py
- honeybee_energy/schedule/typelimit.py
- tests/idealair_test.py
- tests/load_people_test.py
- tests/schedule_typelimit_test.py
This commit brings the library up-to-date with these recent changes in honeybee-schema:
https://github.com/ladybug-tools/honeybee-schema/pull/44
> fix(altnumber): Add NoLimit, AutoCalculate and AutoSize

- honeybee_energy/config.py
- honeybee_energy/construction/air.py
- honeybee_energy/constructionset.py
- honeybee_energy/lib/constructions.py
- honeybee_energy/lib/library/constructions/default.idf
- honeybee_energy/lib/library/schedules/default.idf
- honeybee_energy/lib/materials.py
- honeybee_energy/lib/schedules.py
- honeybee_energy/properties/face.py
- honeybee_energy/properties/model.py
- honeybee_energy/properties/room.py
- honeybee_energy/properties/shade.py
- honeybee_energy/writer.py
- tests/construction_test.py
- tests/constructionset_test.py
- tests/model_extend_test.py
This involved refactoring a few things including the ability to assign schedules to constructions.
> feat(construction): Add AirBoundaryConstruction

- MANIFEST.in
- honeybee_energy/construction/dictutil.py
- honeybee_energy/constructionset.py
- honeybee_energy/dictutil.py
- honeybee_energy/lib/_loadconstructions.py
- honeybee_energy/lib/_loadconstructionsets.py
- honeybee_energy/lib/_loadmaterials.py
- honeybee_energy/lib/_loadprogramtypes.py
- honeybee_energy/lib/_loadschedules.py
- honeybee_energy/lib/_loadtypelimits.py
- honeybee_energy/lib/constructions.py
- honeybee_energy/lib/constructionsets.py
- honeybee_energy/lib/data/constructions/default.idf
- honeybee_energy/lib/data/constructions/default.json
- honeybee_energy/lib/materials.py
- honeybee_energy/lib/programtypes.py
- honeybee_energy/lib/schedules.py
- honeybee_energy/lib/scheduletypelimits.py
- honeybee_energy/load/dictutil.py
- honeybee_energy/material/dictutil.py
- honeybee_energy/properties/model.py
- honeybee_energy/schedule/dictutil.py
- honeybee_energy/simulation/dictutil.py
- tests/dictutil_test.py
This commit includes a number of improvements to the library of objects including:
* It is now possible to change the properties of the default ShadeConstruction and AirBoundaryConstruction by editing honeybee JSON files of these objects
* Utilities that re-serialize any number of a group of objects from_dict have been added. These parallel the putil and mutil libraries of honeybee_radiance. Their presence has cut down on a lot of duplicate code and makes it possible to have a master function that can re-serialize any object.
* A few other bugs have been fixed
> feat(lib): Improve the library of objects

- honeybee_energy/schedule/rule.py
- honeybee_energy/schedule/ruleset.py
- tests/schedule_rule_test.py
- tests/schedule_ruleset_test.py
This commit brings the ScheduleRuleset holiday schema in in line with the OpenStudio SDK.
> feat(ruleset): Refactor ScheduleRuleset to align with OpenStudio SDK

- .travis.yml
- honeybee_energy/config.py
- honeybee_energy/run.py
- honeybee_energy/writer.py
- tests/run_test.py
I also added in a test that runs an IDF through EnergyPlus.
> fix(run): Change to running OpenStudio exe directly

- honeybee_energy/result/colorroom.py
- honeybee_energy/result/sql.py
- tests/result_colorroom_test.py
- tests/result_test.py
This also includes a fix to the SQL parsing module.
> feat(colorroom): Add module to create colored room visualizations

- honeybee_energy/run.py
- honeybee_energy/simulation/output.py
- tests/simulation_output_test.py
I also decided to change the default SimulationParameters to include the html by default.
> fix(output):  Use correct filename for html

- honeybee_energy/result/zsz.py
This was an odd bug I was getting in Grasshopper. This fixes it, though.
> fix(zsz): Fix bug in assignment of metadata

- honeybee_energy/cli/lib.py
- honeybee_energy/cli/simulate.py
- honeybee_energy/cli/translate.py
- tests/cli_translate_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/178
> fix(cli): Change --log-file to --output-file in CLI commands

- honeybee_energy/cli/simulate.py
- honeybee_energy/run.py
This will give Konrad the means of adding the reporting measures into the CLI run.
> fix(cli): Update simulate command to include base_osw

- honeybee_energy/cli/lib.py
- honeybee_energy/measure.py
This will remove a big burden from the Grasshopper component.
> fix(measure): Handle argument type casting in Python

- honeybee_energy/config.json
- honeybee_energy/config.py
- honeybee_energy/run.py
- tests/config_test.py
This commit is coordinated with this one over on the honeybee-openstudio0gem :
ladybug-tools/energy-model-measure#105
> fix(gem): Change the gem name to honeybee-openstudio

- .travis.yml
- honeybee_energy/config.py
- honeybee_energy/simulation/shadowcalculation.py
- tests/simulation_shadowcalculation_test.py
I am also upgrading the dictionary for looking up matching version of E+ and OpenStudio.
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/171
> fix(openstudio): Upgrade ShadowCalculation to OpenStudio 3.0

- honeybee_energy/run.py
- honeybee_energy/writer.py
- tests/json/model_colinear_verts.json
- tests/run_test.py
Resolves https://github.com/ladybug-tools/honeybee-core/issues/64
> fix(tolerance): Remove co-linear vertices before E+ export

- honeybee_energy/result/colorobj.py
- honeybee_energy/result/match.py
I realized that there are likely multiple modules that will make use of these functions and these functions should also eventually handle matching of triangulated apertures and doors.
> syle(match): Pull result matching utilities into their own module

- honeybee_energy/construction/windowshade.py
- tests/construction_test.py
- tests/run_test.py
I added a few more tests for WindowConstructionShade and fixed a few bugs I found in the process.
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/214
> fix(windowshade): Fix several small bugs in WindowConstructionShade

- honeybee_energy/lib/_loadconstructions.py
Looks like I forgot to fix this yesterday.
> fix(lib): Fix bug in loading user construction from lib

- honeybee_energy/lib/_loadconstructions.py
- honeybee_energy/lib/_loadmaterials.py
- honeybee_energy/lib/_loadschedules.py
See here for more info:
https://discourse.ladybug.tools/t/schedules-programs-json/10457/2
> fix(lib): Fix subtle bug in the way the standards load up

- honeybee_energy/hvac/allair/__init__.py
- honeybee_energy/hvac/heatcool/__init__.py
It looks like my last PR left some docstrings incomplete.
> docs(hvac): Fix template HVAC docstrings

- honeybee_energy/ventcool/simulation.py
- tests/ventcool_afn_test.py
It seems my auto-rotation of long_axis_angle was off by 90 degrees.
> fix(afn): Fix bug in previous commit

- honeybee_energy/construction/opaque.py
- honeybee_energy/construction/window.py
See here for more info:
https://discourse.ladybug.tools/t/only-one-material-layer-is-allowed-using-windowmaterialsimpleglazsys/10877/4
> fix(construction): Ensure illegal constructions don't crash import

- honeybee_energy/cli/__init__.py
- honeybee_energy/config.py
I can see this will be useful for debugging down the line.
> style(cli): Add version option to core group

- honeybee_energy/simulation/output.py
- tests/simulation_output_test.py
Thanks to @mingbopeng and @mostapharoudsari for finding this one.
> fix(output): Fix bug in assignment of default outputs

- honeybee_energy/config.py
- honeybee_energy/run.py
I also made a couple of improvements to how energyplus.exe is called, which eliminate the need to copy the epw and idd into the simulation folder.
> feat(run): Add option to Run EnergyPlus silently

- honeybee_energy/material/opaque.py
- tests/material_opaque_test.py
It seems that EnergyPlus need this in order for its calculation to be stable.
> fix(material): Ensure specific heat is greater than 100

- honeybee_energy/cli/baseline.py
- honeybee_energy/construction/dictutil.py
- honeybee_energy/run.py
I am also making use of the new is_detached property in the baseline model commands.
I am also adding in " " around the file paths of all file paths in batch + shell files.
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/401
> fix(construction): Fix wrong re-serilaization of WindowConstructionShade

- honeybee_energy/config.py
This effectively adds support for experimental OpenStudio builds in the Grasshopper plugin.
> fix(config): Parse the version of experimental OpenStudio builds

- honeybee_energy/writer.py
- tests/json/model_5vertex_sub_faces_interior.hbjson
- tests/run_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/47
> fix(writer): Add aperture triangulation in Model.to.idf

- dev-requirements.txt
- honeybee_energy/result/loadbalance.py
- honeybee_energy/simulation/output.py
- tests/material_shade_test.py
- tests/simulation_output_test.py
I am also adding an option to the load balance to use all of the solar gain, which will be particularly important for cases of air boundaries.
> fix(output): Add gains + losses for AFN infiltration

- honeybee_energy/config.py
- honeybee_energy/run.py
Now we will be able to see the E+ simulation progress whenever we run reporting measures.
> fix(run): Use honeybee_adapter to view simulation progress

- honeybee_energy/cli/validate.py
- honeybee_energy/load/_base.py
- honeybee_energy/load/people.py
- tests/cli_validate_test.py
- tests/json/constructionset_complete.json
- tests/json/program_type_office.json
- tests/json/schedule_ruleset_office_occupancy.json
- tests/json/scheduletypelimit_temperature.json
I am also adding in checks for schedule type limits to stop OpenStudio from breaking everything with its "helpful" checks.
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/486
> feat(cli): Add commands to validate various types of objects

- honeybee_energy/cli/baseline.py
- honeybee_energy/cli/result.py
- honeybee_energy/cli/settings.py
I'm improving a few of the options on the CLI in order to work around the lack of if/then logic in queenbee.
> fix(cli): Add better handling of certain options

- cli-requirements.txt
- setup.py
> chore(deps cli): remove extra dependency 

- docs/conf.py
Hi @chriswmackey, as requested here's is the update on the CLI documentation routine. Will work on the other two repos as you suggested next.
> docs(sphinx/conf): support CLI group names not matching CLI file names

- honeybee_energy/load/_base.py
- honeybee_energy/load/daylight.py
- honeybee_energy/properties/room.py
- honeybee_energy/writer.py
- tests/daylight_test.py
- tests/run_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/210
> feat(load): Add a class for Daylight Controls

- honeybee_energy/schedule/rule.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/628
> docs(schedule): Fix incorrect sample in docstring

- docs/conf.py
Hi @chriswmackey,
Finally some update about your revision. I did some comments at the time in response to your revision in the ``lbt-recipies`` PR but since then I think I made some good progress to handle commands without groups. I am not sure if this will be a bullet-proof solution since there may be some future scenarios that I may have not considered yet. I can discuss this further why future implementations inside ``cli\__init__.py`` may trigger issues, it all depends on how unique these scenarios may be. Otherwise, I tested and it did work on a handful of repos so hopefully this is a good revision to start using.
Also I fixed the group naming by looking at the data inside ``cli\__init__.py``. Feel free to try it in ``honeybee-radiance`` or I can send a PR there as well if you …
> fix(sphinx-conf): Fix CLI documentation process

- honeybee_energy/hvac/allair/_base.py
- honeybee_energy/hvac/allair/furnace.py
- honeybee_energy/hvac/allair/psz.py
- honeybee_energy/hvac/allair/ptac.py
- honeybee_energy/hvac/allair/pvav.py
- honeybee_energy/hvac/allair/vav.py
- honeybee_energy/hvac/doas/_base.py
- honeybee_energy/hvac/doas/fcu.py
- honeybee_energy/hvac/doas/vrf.py
- honeybee_energy/hvac/doas/wshp.py
- honeybee_energy/hvac/heatcool/_base.py
- honeybee_energy/hvac/idealair.py
- tests/hvac_allair_test.py
- tests/hvac_doas_test.py
I am also adding a boolean to include humidifiers in order to meet humidification setpoints.
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/625
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/322
> fix(hvac): Add option for demand controlled ventilation

- dev-requirements.txt
We already get click with ladybug-core.
> chore(deps-dev): Remove unnecessary click

- .github/workflows/ci.yaml
- build_image.sh
- dev-requirements.txt
- honeybee_energy/config.py
- honeybee_energy/construction/air.py
- honeybee_energy/properties/model.py
- honeybee_energy/writer.py
- tests/idf/test_shoe_box.idf
It looks like there weren't too many changes. Just an update to Construction:AirBoundary and a change to what energyplus CLI returns for its --version.
I also found and fixed an old bug in the model-to-idf method with air walls.
> feat(openstuido): Upgrade to OpenStudio 3.2

- honeybee_energy/result/loadbalance.py
This will be useful for cases where we want to use unconditioned floor area or net vs. gross area.
> fix(loadbalance): Add the option to override the floor area

- honeybee_energy/result/loadbalance.py
- honeybee_energy/simulation/output.py
- tests/simulation_output_test.py
More info here:
https://discourse.ladybug.tools/t/afn-nat-ventilation-gain-loss/14576/10
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/710
> fix(loadbalance): Ensure that new AFN outputs are included in balance

- .github/workflows/ci.yaml
- build_image.sh
- honeybee_energy/internalmass.py
- honeybee_energy/properties/model.py
- honeybee_energy/properties/room.py
- honeybee_energy/writer.py
- tests/internalmass_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/207
> feat(internalmass): Add module and class for InternalMass

- honeybee_energy/material/glazing.py
This is coordinated with this PR:
https://github.com/ladybug-tools/honeybee-schema/pull/328
> fix(glazing): Allow use of Autocalculate in back reflectance

- honeybee_energy/material/shade.py
Somehow, we had an extra unused property here for shade layers.
> style(material): Remove unused property

- honeybee_energy/hvac/_template.py
- honeybee_energy/hvac/allair/_base.py
- honeybee_energy/hvac/allair/furnace.py
- honeybee_energy/hvac/allair/psz.py
- honeybee_energy/hvac/allair/ptac.py
- honeybee_energy/hvac/allair/pvav.py
- honeybee_energy/hvac/allair/vav.py
- honeybee_energy/hvac/doas/_base.py
- honeybee_energy/hvac/doas/fcu.py
- honeybee_energy/hvac/doas/vrf.py
- honeybee_energy/hvac/doas/wshp.py
- honeybee_energy/hvac/heatcool/_base.py
- honeybee_energy/hvac/heatcool/baseboard.py
- honeybee_energy/hvac/heatcool/evapcool.py
- honeybee_energy/hvac/heatcool/fcu.py
- honeybee_energy/hvac/heatcool/gasunit.py
- honeybee_energy/hvac/heatcool/residential.py
- honeybee_energy/hvac/heatcool/vrf.py
- honeybee_energy/hvac/heatcool/windowac.py
- honeybee_energy/hvac/heatcool/wshp.py
- setup.py
- tests/hvac_allair_test.py
- tests/hvac_doas_test.py
- tests/hvac_heatcool_test.py
Now that the latest versions of ASHRAE 90.1 were added to openstudio-standards, this commit adds these new versions to this package.
> feat(hvac): Add support for 2016 and 2019 HVAC templates

- honeybee_energy/material/_base.py
- honeybee_energy/material/glazing.py
- honeybee_energy/material/opaque.py
- honeybee_energy/properties/model.py
- tests/material_opaque_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/505
Addresses https://discourse.ladybug.tools/t/annualloads-and-windowconstructionshade/15258/6
I am also adding a validation check for constructions in reversed order.
> fix(construction): Add check for possible CTF errors

- honeybee_energy/cli/lib.py
- honeybee_energy/lib/_loadconstructions.py
- honeybee_energy/lib/_loadconstructionsets.py
- honeybee_energy/lib/_loadmaterials.py
- honeybee_energy/lib/_loadprogramtypes.py
- honeybee_energy/lib/_loadschedules.py
- honeybee_energy/lib/_loadtypelimits.py
- honeybee_energy/schedule/fixedinterval.py
This should satisfy what @mingbopeng needs in order to load local user-defined standards with the .NET bindings.
> feat(cli): Add command to get standards folder as ModelEnergyProperties

- honeybee_energy/properties/room.py
- tests/room_extend_test.py
This is useful and will compliment the other absolute methods.
> fix(room): Add a method to apply absolute ventilation

- .github/workflows/ci.yaml
- honeybee_energy/construction/_base.py
- honeybee_energy/construction/opaque.py
- honeybee_energy/construction/window.py
- honeybee_energy/material/opaque.py
- tests/aperture_extend_test.py
- tests/cli_translate_test.py
- tests/construction_test.py
- tests/fixtures/userdata_fixtures.py
I'm also adding in reflectance properties for opaque material layers.
> fix(construction): Enable solar radiation in opaque temperature profile

- honeybee_energy/cli/__init__.py
- honeybee_energy/cli/setconfig.py
- honeybee_energy/cli/simulate.py
- honeybee_energy/config.json
- honeybee_energy/config.py
- honeybee_energy/measure.py
- honeybee_energy/run.py
I also fixed the only known bug of being able to use additional_strings and reporting measures in the same simulation. Lastly, I added commands to set the config variables.
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/250
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/648
> feat(simulate): Add an option to run OpenStudio Results measure

- Dockerfile
- build_image.sh
- setup.py
I'm also trying to get around copying all the test files of the honeybee_openstudio_gem into the docker image.
> fix(docker): Include lbt-measures in the docker image

- honeybee_energy/constructionset.py
- honeybee_energy/schedule/fixedinterval.py
- honeybee_energy/schedule/ruleset.py
There were some bugs that were caught by my Python linter. The implementation of user_data for Face/Wall/Roof sets was buggy and it seemed like there just weren't enough use-cases to justify it so I removed it.
> fix(resource): Fix several bugs in user_data implementation

- honeybee_energy/construction/opaque.py
- honeybee_energy/construction/window.py
- honeybee_energy/material/gas.py
- honeybee_energy/reader.py
- honeybee_energy/schedule/fixedinterval.py
- honeybee_energy/schedule/ruleset.py
- honeybee_energy/schedule/typelimit.py
More info is here:
https://discourse.ladybug.tools/t/add-to-ep-library/16875/12
> fix(idf): Fix the IDF-parsing capabilities of several objects

- honeybee_energy/construction/air.py
- honeybee_energy/ventcool/opening.py
This was causing validation errors with the C# bindings so I think I should just include these properties.
> fix(ventcool): Automatically write flow coeff and exponent into dict

- honeybee_energy/properties/model.py
- honeybee_energy/schedule/ruleset.py
- tests/schedule_ruleset_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/838
> fix(model): Implement better dynamic window grouping

- honeybee_energy/cli/lib.py
- honeybee_energy/hvac/doas/radiant.py
- honeybee_energy/hvac/heatcool/radiant.py
- honeybee_energy/lib/_loadconstructions.py
- honeybee_energy/lib/_loadprogramtypes.py
- honeybee_energy/properties/model.py
- tests/model_extend_test.py
I'm also fixing a couple of bugs and enabling the load_energy_properties_from_dict method to accept any empty variable.
> fix(model): Add dump_properties_to_dict method to ModelEnergyProperties

- honeybee_energy/run.py
I think I have finally nailed down what is needed to run OpenStudio out of folders with non-ASCII characters. I needed to:
1. Make sure that the OpenStudio Workflow JSON is encoded as UTF-8
2. If the command calling the OpenStudio CLI contains non-ASCII characters, I need to run it with subprocess instead of a .bat file.
I noticed that the simulation is still significantly faster on Windows when it's run with .bat files instead of with subprocess so I will still use this .bat pathway when I don't detect any non-ASCII characters in the command to call the OpenStudio CLI.
> fix(run): Enable simulation to run out of Non-ASCII folders

- honeybee_energy/hvac/doas/radiant.py
- honeybee_energy/hvac/heatcool/radiant.py
This should be popular for a lot of residential modeling.
> fix(hvac): Add support for radiant wooden floors

- honeybee_energy/_extend_honeybee.py
- honeybee_energy/boundarycondition.py
- honeybee_energy/writer.py
- tests/boundarycondition_test.py
Resolved https://github.com/ladybug-tools/honeybee-energy/issues/407
> feat(boundarycondition): Add Boundary Condition for OtherSideTemperature

- honeybee_energy/construction/window.py
- honeybee_energy/material/dictutil.py
- honeybee_energy/properties/aperture.py
- honeybee_energy/properties/door.py
- honeybee_energy/properties/face.py
- honeybee_energy/properties/model.py
- honeybee_energy/run.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/209
> fix(frames): Add several fixes for window frames

- honeybee_energy/result/loadbalance.py
- honeybee_energy/simulation/output.py
- tests/simulation_output_test.py
More information is here:
https://discourse.ladybug.tools/t/understanding-the-load-balance-component-assumptions/19322/26?u=chris
> fix(loadbalance): Request correct natural ventilation outputs

- honeybee_energy/properties/model.py
This ensures that people can still use the OpenStudio pathway for exporting partial models to gbXML.
> fix(model): Ensure lack of rooms does not stop OSM export

- .github/workflows/ci.yaml
- build_image.sh
This also updates the docker image to use OpenStudio 3.5
> fix(ci): Update CI to use OpenStudio 3.5

- honeybee_energy/construction/windowshade.py
- honeybee_energy/properties/extension.py
- tests/construction_extend_test.py
Add .properties and other required methods to support custom properties
> feat(properties) add .properties to WindowConstructionShade class

- honeybee_energy/measure.py
- tests/measure/tbd/LICENSE.md
- tests/measure/tbd/README.md
- tests/measure/tbd/measure.rb
- tests/measure/tbd/measure.xml
- tests/measure_test.py
It looks like the previous method of casting the text to boolean was not working correctly.
> fix(measure): Ensure that default values for boolean inputs are correct

- honeybee_energy/cli/translate.py
- honeybee_energy/load/people.py
- honeybee_energy/properties/model.py
- honeybee_energy/run.py
- tests/cli_translate_test.py
I am also adding commands to translate to SDD
> fix(model): Add validation for various aspects of Detailed HVAC

- honeybee_energy/properties/model.py
- honeybee_energy/properties/room.py
- honeybee_energy/ventcool/fan.py
- honeybee_energy/ventcool/opening.py
- honeybee_energy/writer.py
- tests/ventcool_fan_test.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/321
> feat(ventcool): Add a class to model fan-based ventilative cooling

- honeybee_energy/load/setpoint.py
- honeybee_energy/properties/model.py
More information is here:
https://discourse.ladybug.tools/t/mismatch-openstudio-vs-honeybee-energy/25223
> fix(model): Add a check for very weird Space Type bug in OpenStudio

- honeybee_energy/cli/translate.py
- honeybee_energy/run.py
It seems TRACE really cannot handle real geometry and it must be heavily simplified for it to accept it.
> fix(run): Greatly simplify geometry for TRACE

- honeybee_energy/construction/air.py
- honeybee_energy/properties/extension.py
Hi @chriswmackey , adding the typical Properties for extension to AirBoundaryConstructions
@ed-p-may
> Add new AirBoundaryConstructionProperties

- honeybee_energy/_extend_honeybee.py
- honeybee_energy/writer.py
- tests/aperture_extend_test.py
- tests/door_extend_test.py
- tests/face_extend_test.py
- tests/model_extend_test.py
- tests/room_extend_test.py
- tests/shade_extend_test.py
- tests/shade_mesh_extend_test.py
Just tweaking a few things that have been bugging me about the writer module. This helps make things more consistent across the extensions and I think it also makes sense from a user perspective.
> style(writer): Reorganize the to_idf methods

- honeybee_energy/properties/model.py
- honeybee_energy/run.py
- honeybee_energy/writer.py
This way, the same method can be used in both direct-to-idf and OpenStudio translators.
> fix(model): Pull zone resolution out into its own method
